### PR TITLE
Faq jaswanthreddypadala

### LINKED ISSUE #24: [feature request]: Create FAQ Section
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the feature.

Create an FAQ section on the Homepage.

### Problem/Motivation.

It would help users learn how to use the app. Users may have common questions and FAQ can be helpful for them.

### Possible Solution/Pitch.

Since the frontend is using Bootstrap, I suggest using [Bootstrap Accordion](https://getbootstrap.com/docs/5.1/components/accordion/) for the section.
Also, add a Navbar menu that links to this section.

### Anything else?

_No response_

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by JaswanthReddyPadala**
# Description

FAQ section is added to the home page.

Fixes #24 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if any)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

# Event

- [x] Hacktoberfest 2021

### CODE REVIEW

**Comment by ashutoshkrris** [comment]
Hey @JaswanthReddyPadala 
Could you please share a screenshot of the output?

**Comment by JaswanthReddyPadala** [comment]
Hey, When I try to run now. I got this problem.
`Traceback (most recent call last):
  File "f:/JR PROJECTS/hacktoberfest2021/EazyLoader/main.py", line 1, in <module>
    from core import app
  File "f:\JR PROJECTS\hacktoberfest2021\EazyLoader\core\__init__.py", line 1, in <module>
    from core.utils.momentjs import momentjs
  File "f:\JR PROJECTS\hacktoberfest2021\EazyLoader\core\utils\momentjs.py", line 1, in <module>
    from jinja2 import Markup
ModuleNotFoundError: No module named 'jinja2'`

But I already installed all requirements. Can you suggest me to fix this.

**Comment by ashutoshkrris** [comment]
If you have installed all the requirements using `Pipfile` or `requirements.txt`, it should have worked.
Anyways, you can install Jinja2 as:
```bash
pip install jinja2
```
Or 
```bash
pipenv install jinja2
```
Choose the according according to the steps followed by you during virtual environment setup

**Comment by JaswanthReddyPadala** [comment]
Yeah, I checked that. Even I reinstalled "jinja2" also. But still It isn't working.

**Comment by ashutoshkrris** [comment]
No worries
I'll merge the PR

**Pull request merged**
